//
// Created by DefTruth on 2022/5/22.
//

#ifndef LITE_AI_TOOLKIT_PIPELINE_FACE_TRACKING_PL_H
#define LITE_AI_TOOLKIT_PIPELINE_FACE_TRACKING_PL_H

#endif //LITE_AI_TOOLKIT_PIPELINE_FACE_TRACKING_PL_H
