//
// Created by DefTruth on 2021/11/27.
//

#ifndef LITE_AI_TOOLKIT_NCNN_CV_NCNN_EFFICIENT_EMOTION8_H
#define LITE_AI_TOOLKIT_NCNN_CV_NCNN_EFFICIENT_EMOTION8_H

#endif //LITE_AI_TOOLKIT_NCNN_CV_NCNN_EFFICIENT_EMOTION8_H
