//
// Created by DefTruth on 2021/11/13.
//

#ifndef LITE_AI_TOOLKIT_NCNN_CV_NCNN_GLINT_COSFACE_H
#define LITE_AI_TOOLKIT_NCNN_CV_NCNN_GLINT_COSFACE_H

#endif //LITE_AI_TOOLKIT_NCNN_CV_NCNN_GLINT_COSFACE_H
