//
// Created by DefTruth on 2021/11/10.
//

#ifndef LITE_AI_TOOLKIT_NCNN_CV_NCNN_YOLOV5_V6_0_H
#define LITE_AI_TOOLKIT_NCNN_CV_NCNN_YOLOV5_V6_0_H

#endif //LITE_AI_TOOLKIT_NCNN_CV_NCNN_YOLOV5_V6_0_H
