//
// Created by DefTruth on 2021/11/14.
//

#ifndef LITE_AI_TOOLKIT_NCNN_CV_NCNN_MOBILESE_FOCAL_FACE_H
#define LITE_AI_TOOLKIT_NCNN_CV_NCNN_MOBILESE_FOCAL_FACE_H

#endif //LITE_AI_TOOLKIT_NCNN_CV_NCNN_MOBILESE_FOCAL_FACE_H
