//
// Created by DefTruth on 2022/4/9.
//

#ifndef LITE_AI_TOOLKIT_NCNN_CV_NCNN_BACKGROUNDMATTINGV2_H
#define LITE_AI_TOOLKIT_NCNN_CV_NCNN_BACKGROUNDMATTINGV2_H

#endif //LITE_AI_TOOLKIT_NCNN_CV_NCNN_BACKGROUNDMATTINGV2_H
