//
// Created by DefTruth on 2022/6/29.
//

#ifndef LITE_AI_TOOLKIT_ORT_CV_FACE_PARSING_BISENET_DYN_H
#define LITE_AI_TOOLKIT_ORT_CV_FACE_PARSING_BISENET_DYN_H

#endif //LITE_AI_TOOLKIT_ORT_CV_FACE_PARSING_BISENET_DYN_H
