//
// Created by DefTruth on 2022/6/3.
//

#ifndef LITE_AI_TOOLKIT_ORT_CV_FEMALE_PHOTO2CARTOON_H
#define LITE_AI_TOOLKIT_ORT_CV_FEMALE_PHOTO2CARTOON_H

#endif //LITE_AI_TOOLKIT_ORT_CV_FEMALE_PHOTO2CARTOON_H
