//
// Created by DefTruth on 2021/11/27.
//

#ifndef LITE_AI_TOOLKIT_TNN_CV_TNN_EMOTION_FERPLUS_H
#define LITE_AI_TOOLKIT_TNN_CV_TNN_EMOTION_FERPLUS_H

#endif //LITE_AI_TOOLKIT_TNN_CV_TNN_EMOTION_FERPLUS_H
