//
// Created by DefTruth on 2021/11/27.
//

#ifndef LITE_AI_TOOLKIT_TNN_CV_TNN_MOBILE_EMOTION7_H
#define LITE_AI_TOOLKIT_TNN_CV_TNN_MOBILE_EMOTION7_H

#endif //LITE_AI_TOOLKIT_TNN_CV_TNN_MOBILE_EMOTION7_H
