//
// Created by DefTruth on 2021/11/21.
//

#ifndef LITE_AI_TOOLKIT_TNN_CV_TNN_FACE_LANDMARKS_1000_H
#define LITE_AI_TOOLKIT_TNN_CV_TNN_FACE_LANDMARKS_1000_H

#endif //LITE_AI_TOOLKIT_TNN_CV_TNN_FACE_LANDMARKS_1000_H
