//
// Created by DefTruth on 2022/3/27.
//

#ifndef LITE_AI_TOOLKIT_MNN_CV_MNN_INSECTID_H
#define LITE_AI_TOOLKIT_MNN_CV_MNN_INSECTID_H

#include "lite/mnn/core/mnn_core.h"

namespace mnncv
{
  class LITE_EXPORTS MNNInsectID : public BasicMNNHandler
  {
  public:
    explicit MNNInsectID(const std::string &_mnn_path, unsigned int _num_threads = 1); //
    ~MNNInsectID() override = default;

  private:
    const float mean_vals[3] = {0.485f * 255.f, 0.456f * 255.f, 0.406f * 255.f};
    const float norm_vals[3] = {(1.0f / 0.229f) * (1.0 / 255.f),
                                (1.0f / 0.224f) * (1.0 / 255.f),
                                (1.0f / 0.225f) * (1.0 / 255.f)};

  private:
    void initialize_pretreat(); //

    void transform(const cv::Mat &mat) override; // resize & normalize.

  public:
    void detect(const cv::Mat &mat, types::ImageNetContent &content, unsigned int top_k = 5);

  private:
    const char *class_names[2037] = {
        "Pseudoscorpiones", "Diplopoda", "Megymenum", "Cicadellidae", "Bothrogonia addita", "Bothrogonia ferruginea", "Cicadella viridis",
        "Maiestas dorsalis", "Nephotettix cincticeps", "Mileewa", "Ledra", "Olidiana brevis", "Acanthosoma denticaudum",
        "Sastragala esakii", "Neolethaeus dallasi", "Metochus uniguttatus", "Metochus abbreviatus", "Horridipamera inconspicua",
        "Geocoris pallidipennis", "Geocoris varius", "Clovia", "Omalophora pectoralis", "Ricaniidae", "Ricaniidae", "Ricanula pulverosa",
        "Ricania speculum", "Euricania facialis", "Ricania guttata", "Ricanula sublimata", "Euricania ocella", "Ricania taeniata",
        "Euricania clara", "Ricania simulans", "Urochela quadrinotata", "Cercopidae", "Cosmoscarta", "Cosmoscarta abdominalis",
        "Cosmoscarta exultans", "Cosmoscarta dimidiata", "Cosmoscarta dorsimacula", "Callitettix versicolor", "Reduviidae",
        "Haematoloecha nigrorufa", "Platymeris", "Agriosphodrus dohrni", "Euagoras plagiatus", "Yolinus albopustulatus",
        "Sycanus croceovittatus", "Sphedanolestes impressicollis", "Epidaus", "Epidaus sexspinus", "Vesbius sanguinosus", "Acanthaspis",
        "Isyndus obscurus", "Sirthenea flavipes", "Ectrychotes andreae", "Sclomina erinacea", "Issidae", "Phymatidae", "Miridae",
        "Eurystylus coelestialium", "Apolygus lucorum", "Helopeltis cinchonae", "Eucorysses grandis", "Hyperoncus lateritius",
        "Poecilocoris nepalensis", "Poecilocoris sanszeusignatus", "Poecilocoris druraei", "Poecilocoris latus", "", "Poecilocoris lewisi",
        "", "Tetrarthria variegata", "Sphaerocoris annulus", "Scutellera amethystina(Scutellera fasciata)", "Chrysocoris stollii",
        "Lamprocoris lateralis", "Calliphara nobilis", "Cantao ocellatus", "Pyrrhocoridae", "Pyrrhocoris sibiricus", "Macrocheraia grandis",
        "Physopelta quadriguttata", "Physopelta gutta", "", "Dysdercus decussatus", "Dysdercus cingulatus", "Dysdercus poecilus",
        "Dindymus rubiginosus", "Dindymus brevis", "Antilochus coquebertii", "Coreidae", "Mictis tenebrosa", "Mictis gallina",
        "Mictis serina", "Mictis fuscipes", "Paradasynus spinosus", "Homoeocerus unipunctatus", "Homoeocerus dilatatus",
        "Homoeocerus striicornis", "Molipteryx", "Molipteryx lunata", "Cletus", "Acanthocoris scaber", "Riptortus", "Riptortus pedestris",
        "Plinachtus bicoloripes", "Notobitus meleagris", "Tingidae", "Corythucha ciliata", "Corythucha marmorata", "Anthocoris confusus",
        "Eurostus", "", "Tessaratoma papillosa", "", "Borysthenes maculatus", "Flatidae", "Cerynia maria", "Lawana imitata",
        "Geisha distinctissima", "Salurnis marginella", "Pyrops", "Pyrops spinolae", "Pyrops watanabei", "Pyrops watanabei",
        "Pyrops candelaria", "Penthicodes atomaria", "Lycorma delicatula", "Lycorma delicatula", "Penthicodes pulchella", "Saiva bullata",
        "Cicadidae", "Cicadidae", "Talainga chinensis", "Meimuna", "Gaeana maculata", "Hyalessa maculaticollis", "Scieroptera",
        "Sulphogaeana sulphurea", "Polymeura chenni", "Chremistica ochracea", "Platypleura kaempferi", "Tacua speciosa",
        "Formotosena seebohmi", "Huechys sanguinea", "Cryptotympana atrata", "Nepidae", "Eysarcoris", "Eysarcoris guttigerus",
        "Eysarcoris aeneus", "Eysarcoris ventralis", "Metonymia glandulosa", "Palomena viridissima", "Priassus spiniger", "Dalpada",
        "Lelia decempunctata", "Dolycoris baccarum", "Eurydema gebleri", "Plautia", "Cazira", "Nezara", "Carpocoris purpureipennis",
        "Menida violacea", "Palomena prasina", "Catacanthus incarnatus", "Alcimocoris", "Halyomorpha halys", "Eurydema dominulus",
        "Zicrona caerulea", "", "Graphosoma rubrolineatum", "Erthesina fullo", "", "Derbidae", "Diostrombus politus", "Membracidae",
        "Dictyopharidae", "Kirkaldyia deyrollei", "Berytidae", "Lygaeus equestris", "Spilostethus hospes", "Tropidothorax elegans",
        "Lygaeus hanseni", "Graptostethus servus", "Gerridae", "Plataspidae", "Tipulidae", "", "Tephritidae", "Tachinidae", "Chironomidae",
        "Stratiomyidae", "Ptecticus aurifer", "Hermetia illucens", "Liriomyza sativae", "Anthomyia illocata", "Culicidae", "Psychodidae",
        "Bombyliidae", "Muscidae", "Asilidae", "Microstylum oberthurii", "Syrphidae", "Eupeodes nitens", "Eupeodes corollae",
        "Eristalinus arvorum", "Eristalis cerealis", "Ischiodon scutellaris", "Eristalis arbustorum", "Phytomia zonata", "Phytomia errans",
        "Syrphus torvus", "Paragus crenulatus", "Syrphus ribesii", "Eristalinus quinquestriatus", "Episyrphus balteatus",
        "Helophilus pendulus", "Corydalidae", "", "Neochauliodes", "", "", "Trichoptera", "Opiliones", "Ornebius kanetataki",
        "Eucriotettix oculatus", "Tetrix japonica", "Erianthus dohrni", "Acrida cinerea", "Oedaleus infernalis", "Chondracris rosea",
        "Trilophidia annulata", "Xenocatantops brachycerus", "Oxya chinensis", "Shirakiacris", "Stauroderus scalaris",
        "Aiolopus thalassinus tamulus", "Pseudoxya diminuta", "Ceracris nigricornis", "Locusta migratoria", "Aularches miliaris", "Patanga",
        "", "Tettigoniidae", "Pseudophyllus titan", "", "Ducetia japonica", "Hexacentrus unicolor", "", "", "Conocephalus melaenus", "",
        "Gampsocleis sedakovii", "Phaneroptera falcata", "Sanaa intermedia", "Gryllacrididae", "Xenogryllus marmoratus",
        "Teleogryllus mitratus", "Gryllus bimaculatus", "Teleogryllus emma", "Atractomorpha sinensis", "", "", "", "Ixodida", "Phasmatodea",
        "Porcellio", "Lepismatidae", "Nemopteridae", "Chrysopidae", "Myrmeleontidae", "Psychopsidae", "Ascalaphidae",
        "Ascalaphus sibiricus", "Mantispidae", "Hemerobiidae", "Tenthredinidae", "Scolia superciliaris", "Ichneumonidae", "Megarhyssa",
        "Xanthopimpla", "Brachymeria minuta", "Liris aurulentus", "", "Ampulex compressa", "Sphex argentatus", "Sceliphron madraspatanum",
        "Sphex subtruncatus", "Sceliphron javanum", "Vespidae", "Parapolybia nodosa", "Parapolybia varia", "Polistes snelleni",
        "Polistes japonicus", "Polistes gigas", "Polistes jokahamae", "Vespa velutina", "Vespa mandarinia", "Vespa affinis", "Polistinae",
        "Vespula flaviceps", "Formicidae", "Pseudoneoponera rufipes", "Oecophylla smaragdina", "Mutillidae", "Pompilidae", "Apidae",
        "Xylocopinae", "Bombus", "Bombus pyrosoma", "Bombus picipes", "Amegilla calceifera", "Delta esuriens", "Phimenes flavopictus",
        "Oreumenes decoratus", "Delta pyriforme", "Chrysididae", "Scutigeridae", "Scolopendridae", "Ephemeroptera", "Araneae", "Araneidae",
        "Araneus diadematus", "Araneus ventricosus", "Macracantha arcuata", "Neoscona mellotteei", "Gasteracantha hasselti",
        "Gasteracantha kuhli", "Gasteracantha diadesmia", "Nephila pilipes", "", "Neoscona vigilans", "Argiope", "Argiope amoena",
        "Araneus ejusmodi", "Araneus mitificus", "Heteropoda venatoria", "Pholcidae", "Macrothele raveni", "Agelenidae", "Lycosidae",
        "Steatoda nobilis", "Latrodectus tredecimguttatus", "Tetragnathidae", "Leucauge tessellata", "", "Ebrechtella tricuspidata",
        "Salticidae", "Thiania bhamoensis", "Telamonia caprina", "Plexippoides", "Siler semiglaucus", "Pancorius crassipes", "Epeus",
        "Hasarius adansoni", "Phintella bifurcilinea", "Cheliceroides longipalpis", "Plexippus paykulli", "", "Eresidae", "Blattodea",
        "Periplaneta australasiae", "Periplaneta americana", "Periplaneta fuliginosa", "Blattella germanica", "Corydidae",
        "Indolestes peregrinus", "Indolestes cyaneus", "Chlorogomphus papilio", "", "Platycnemididae", "Copera annulata",
        "Coeliccia cyanomelas", "Pseudolestes mirabilis", "Gomphidae", "Sinictinogomphus clavatus", "Ictinogomphus rapax",
        "Gomphidia confluens", "", "Philoganga vetusta", "Euphaea decorata", "Calopterygidae", "Calopteryx splendens",
        "Neurobasis chinensis", "Matrona basilaris", "Calopteryx virgo", "Mnais", "Mnais mneme", "Archineura incarnata",
        "Atrocalopteryx atrata", "Anax guttatus", "Anax parthenope", "Anax immaculifrons", "Anax nigrofasciatus", "Gynacantha japonica",
        "Gynacantha subinterrupta", "Aeshna mixta", "Rhyothemis", "Rhyothemis variegata", "Rhyothemis fuliginosa", "Tholymis tillarga",
        "Palpopleura sexmaculata", "Tramea virginia", "Deielia phaon", "Tetrathemis platyptera", "Sympetrum vulgatum",
        "Indothemis carnatica", "Potamarcha congener", "Orthetrum", "Orthetrum chrysis", "Orthetrum luzonicum", "Orthetrum melania",
        "Orthetrum poecilops", "Orthetrum sabina", "Orthetrum albistylum", "Orthetrum cancellatum", "Orthetrum lineostigma",
        "Orthetrum pruinosum", "Orthetrum glaucum", "Orthetrum triangulare", "Pseudothemis zonata", "Crocothemis servilia",
        "Zyxomma petiolatum", "Neurothemis taiwanensis", "Neurothemis tullia", "Neurothemis fulvia", "Neurothemis intermedia",
        "Diplacodes trivialis", "Brachydiplax chalybea", "Trithemis festiva", "Trithemis aurora", "Sympetrum croceolum",
        "Sympetrum parvulum", "Sympetrum risi", "Sympetrum eroticum", "Sympetrum pedemontanum", "Sympetrum danae", "Acisoma panorpoides",
        "Lyriothemis pachygastra", "Epophthalmia elegans", "Brachythemis contaminata", "Pantala flavescens", "Selysiothemis nigra",
        "Pseudagrion rubriceps", "Ceriagrion fallax", "Ischnura asiatica", "Ischnura senegalensis", "Ischnura rufostigma",
        "Ischnura aurora", "Agriocnemis femina", "Enallagma cyathigerum", "Paracercion calamorum", "Ceriagrion nipponicum",
        "Agriocnemis pygmaea", "Chlorocyphidae", "Heliocypha perforata", "Scorpiones", "Heterometrus petersii", "Mantodea",
        "Pseudocreobotra wahlbergi", "Phyllocrania paradoxa", "Acromantis japonica", "Creobroter", "Sibylla pretiosa",
        "Hymenopus coronatus", "Tenodera sinensis", "Tenodera aridifolia", "Phyllothelys", "Hierodula patellifera", "Mantis religiosa",
        "Statilia maculata", "Plecoptera", "Mecoptera", "", "Trictenotomidae", "Rutelidae", "Anomala", "Popillia",
        "Eumorphus quadriguttatus", "Attelabidae", "Byctiscus betulae", "Paratrachelophorus nodicornis", "Tomapoderus ruficollis",
        "Apoderus coryli", "Aspidobyctiscus lacunipennis", "Trachelophorus giraffa", "Elateridae", "Campsosternus", "Campsosternus gemma",
        "Chrysomelidae", "Gallerucida bifasciata", "Monolepta quadriguttata", "Chrysomela populi", "Chrysomela vigintipunctata",
        "Plagiodera versicolora", "Oides decempunctata", "Oides bowringii", "Colasposoma dauricum", "Leptinotarsa decemlineata",
        "Sagra femorata", "Agasicles hygrophila", "Criocerinae", "", "Chrysolina polita", "Chaetocnema hortensis", "Aulacophora indica",
        "Monolepta signata", "Phyllotreta striolata", "Diabrotica undecimpunctata", "Podontia lutea", "Aulacophora lewisii",
        "Gastrolina thoracica", "Aulacophora nigripennis", "Buprestidae", "Chrysochroa fulgidissima", "Agrilus planipennis", "Chalcophora",
        "Cerambycidae", "Thysia", "Monochamus saltuarius", "Leptura duodecimguttata", "Lamiomimus gottschei", "Moechotypa diphysis",
        "Xystrocera globosa", "Mesosa myops", "Dorysthenes", "Monochamus alternatus", "Polyzonus fasciatus", "Agapanthia amurensis",
        "Stenocorus meridianus", "Acanthocinus griseus", "Leptura thoracica", "Apomecyna saltator", "Anoplophora", "Anoplophora horsfieldi",
        "Leptura annularis", "Rhytiphora bankii", "Semanotus bifasciatus", "Strangalia attenuata", "Neocerambyx raddei",
        "Pterolophia annulata", "Glenea relicta", "Imantocera penicillata", "Eupromus ruber", "Aristobia horridula",
        "Dicelosternus corallinus", "Batocera", "", "Batocera rubus", "Glenea cantor", "Oberea", "Olenecamptus", "Apriona rugicollis",
        "Apriona swainson", "Purpuricenus temminckii", "Callidium violaceum", "Chlorophorus", "Chlorophorus douei",
        "Chlorophorus annularis", "Chlorophorus signaticollis", "Eucomatocera vittata", "Xylotrechus", "Xylotrechus yanoi",
        "Xylotrechus rusticus", "Asemum striatum", "Paraglenea fortunei", "Phytoecia rufiventris", "Xylorhiza", "", "Aegosoma",
        "Arhopalus rusticus", "Stromatium longicorne", "Macrochenus guerini", "Euryphagus", "Saperda populnea", "Aromia bungii",
        "Tetraopes tetrophthalmus", "Thyestilla gebleri", "Psacothea", "Paraleprodera diophthalma", "", "", "Tenebrionidae", "Lagriinae",
        "Blaps rynchopetera", "", "", "Carabidae", "Therates fruhstorferi", "Pheropsophus", "Carabus lafossei", "Carabus elysii",
        "Carabus smaragdinus", "Scarites", "Dolichus halensis", "Chlaenius", "Carabus brandti", "Dynastidae", "Allomyrina dichotoma",
        "Oryctes rhinoceros", "Xylotrupes gideon", "", "Eupatorus gracilicornis", "Trichogomphus mongol", "Oryctes nasicornis",
        "Dynastes hercules", "Coccinellidae", "Coccinellidae", "Coccinella septempunctata", "Aiolocaria hexaspilota",
        "Cheilomenes sexmaculata", "Oenopia formosana", "Vibidia duodecimguttata", "Coccinula quatuordecimpustulata",
        "Coelophora biplagiata", "Calvia muiri", "Propylaea quatuordecimpunctata", "Illeis koebelei", "Henosepilachna vigintioctopunctata",
        "Oenopia conglobata", "Halmus chalybeus", "Henosepilachna vigintioctomaculata", "Propylea japonica", "Lasioderma serricorne",
        "Geotrupidae", "Eumolpidae", "Platycorynus parryi", "Smaragdina nigrifrons", "Euchiridae", "Cheirotonus gestroi",
        "Cheirotonus jansoni", "Meloidae", "Lytta caraganae", "Epicauta", "", "Themus", "Cetoniidae", "Euselates", "Goliathus",
        "Gametis jucunda", "Pseudotorynorrhina japonica", "Protaetia", "Clinterocera mandarina", "Dicronorhina derbyana",
        "Glycyphana horsfieldi", "Agestrata orichalca", "Rhomborhina", "Campsiura mirabilis", "Dicronocephalus adamsi",
        "Dicronocephalus wallichii", "Dicronocephalus bowringi", "Pyrocoelia", "Pyrocoelia analis", "Silphidae", "Collyris", "Tricondyla",
        "Cicindela", "Cicindela chinenesis", "Cicindela separata", "Cicindela gemmata", "Cicindela aurulenta", "Aphodius fimetarius",
        "Bruchidae", "Curculionidae", "Cryptorhynchus lapathi", "Sipalinus gigas", "Eucryptorrhynchus", "Cylas formicarius", "",
        "Sitophilus oryzae", "Rhynchophorus ferrugineus", "Hypomeces pulviger", "Pyrochroidae", "Cleridae", "Trichodes sinae",
        "Scarabaeoidea", "Hispidae", "Cassida rubiginosa", "Chiridopsis bowringii", "Aspidimorpha miliaris", "Aspidimorpha furcata",
        "Aspidimorpha sanctaecrucis", "Taiwania circumdata", "Laccoptera nepalensis(Laccoptera quadrimaculata)", "Cassida nebulosa",
        "Lucanidae", "Dorcus titanus", "Dorcus hopei", "Neolucanus", "Neolucanus swinhoei", "", "Lucanus", "Prosopocoilus confucius",
        "Prosopocoilus astacoides", "Prosopocoilus girafa", "Prosopocoilus biplagiatus", "Odontolabis cuvera", "Odontolabis siva",
        "Eucorynus crassicornis", "Bolboceratidae", "Staphylinidae", "Melolonthidae", "Polyphylla", "Polyphylla decemlineata",
        "Melolontha hippocastani", "Amphimallon solstitiale", "Dytiscidae", "Uropygi", "Heliodinidae", "Epicopeia mencia",
        "Epicopeia hainesii", "Papilionidae", "Sericinus montelus", "Papilio krishna", "Papilio glaucus", "", "Papilio multicaudata",
        "Papilio hermosanus", "Papilio ulysses", "Papilio nephelus", "Papilio paris", "Papilio dehaanii", "Papilio prexaspes",
        "Papilio xuthus", "", "Papilio polytes", "Papilio helenus", "Papilio castor", "Papilio bianor", "Papilio dialis",
        "Papilio arcturus", "Papilio alcmenor", "Papilio maackii", "Papilio memnon", "Papilio macilentus", "Papilio cresphontes",
        "Papilio protenor", "Papilio demoleus", "Papilio hoppo", "Papilio machaon", "", "Papilio troilus", "Pazala", "Pazala eurous",
        "Pazala mullah", "Teinopalpus imperialis", "Teinopalpus aureus", "Agehana elwesi", "Bhutanitis thaidina", "Bhutanitis ludlowi",
        "Bhutanitis lidderdalii", "Chilasa clytia", "Chilasa clytia", "Iphiclides podalirius", "Atrophaneura horishana",
        "Atrophaneura varuna", "Lamproptera curius", "Lamproptera meges", "Pachliopta aristolochiae", "Trogonoptera brookiana",
        "Pathysa agetes", "Pathysa_antiphates", "Luehdorfia chinensis", "Troides magellanus", "Troides helena", "Troides aeacus",
        "Meandrusa sciron", "Meandrusa payeni", "Losaria coon", "Graphium", "Graphium cloanthus", "Graphium doson", "Graphium chironides",
        "Graphium nomius", "Graphium megarus", "Graphium agamemnon", "Graphium sarpedon", "Graphium leechi", "Eurytides marcellus", "Byasa",
        "Byasa confusa", "Byasa hedistus", "Byasa polyeuctes", "Byasa mencius", "Byasa dasarada", "Byasa impediens", "Byasa alcinous",
        "Limacodidae", "", "Chalcoscelides castaneipars", "Ceratonema", "Thosea", "Matsumurides", "Iragoides conjuncta", "",
        "Narosoideus flavidorsalis", "Iraga rugosa", "Rhamnosa uniformis", "Scopelodes venosa", "Scopelodes contracta", "", "Narosa",
        "Phocoderma velutina", "Parasa", "Parasa bicolor", "Parasa bicolor", "Parasa lepida", "", "Parasa darma", "Parasa consocia", "",
        "Parasa pastoralis", "", "Belippa horrida", "Demonarosa rufotessellata", "Setora postornata", "", "Setora baibarana",
        "Miresa bracteata", "Miresa fulgida", "Hyphorma minax", "Monema flavescens", "Monema flavescens", "Thosea sinensis",
        "Thosea sinensis", "Tortricidae", "Gypsonoma minutana", "Loboschiza koenigiana", "Eupoecilia ambiguella", "Epiblema foenella",
        "Eucosma campoliliana", "Cerace xanthocosma", "Grapholita delineana", "Libythea lepita", "Libythea myrrha", "Noctuidae",
        "Chalciope geometrica", "Chalciope mygdon", "Chalciope hyppasia", "Anomis mesogona", "Hadjina chinensis",
        "Thysanoplusia intermixta", "Sphragifera sigillata", "Chytonix segregata", "Anisoneura aluco", "Sarbanissa subflava",
        "Daddala lucilla", "Cucullia fraterna", "Pericyma cruegeri", "Acronicta tridens", "Acronicta tridens", "Acronicta cuspis",
        "Acronicta euphorbiae", "Acronicta euphorbiae", "Acronicta alni", "Acronicta alni", "Acronicta rumicis", "Acronicta rumicis",
        "Acronicta hercules", "Acronicta denticulata", "Acronicta psi", "Acronicta psi", "Acronicta pruinosa", "Acronicta pruinosa",
        "Acronicta megacephala", "Acronicta megacephala", "Supersypnoides simplex", "Conservula indica", "Hypopyra vespertilio",
        "Mimeusemia vilemani", "Mimeusemia vilemani", "Asota heliconia", "Asota heliconia", "Hylophilodes tsukusensis", "Paracolax fentoni",
        "Paracolax sugii", "Corgatha nitens", "Corgatha dictaria", "Ophiusa coronata", "Ophiusa tirhaca", "Protoschinia scutosa",
        "Agrotis ipsilon", "Oruza albigutta", "Parallelia arctotaenia", "Parallelia stuposa", "Parallelia maturata", "Phyllodes imperialis",
        "Staurophora celsia", "Episteme vetula", "Episteme lectrix", "Episteme adulatrix", "Lopharthrum comprimens", "Asota tortuosa",
        "Mimeusemia persimilis", "Tiracola plagiata", "Callopistria nobilior", "Callopistria repleta", "Eligma narcissus", "",
        "Spirama retorta", "Sphragifera biplagiata", "Lophoptera squamigera", "Ercheia cyllaria", "Axylia putris", "Ramadasa pavo",
        "Adris tyrannus", "Hydrillodes lentalis", "Diarsia canescens", "Diarsia subtincta", "Brithys crini", "", "Mocis frugalis",
        "Mocis undata", "Spodoptera depravata", "Macdunnoughia purissima", "Spodoptera picta", "Spodoptera litura", "Spodoptera pecten",
        "Narangodes argyrostrigatus", "Athetis lepigone", "Xanthodes transversa", "", "Mamestra brassicae", "Spodoptera exigua", "Bocula",
        "Cosmia restituta", "Aedia leucomelas", "Phlogophora albovittata", "Trachea auriplena", "Ctenoplusia albostriata",
        "Pangrapta lunulata", "Edessena gentiusalis", "Erebus macrops", "Erebus pilosa", "Erebus albicincta", "Erebus caprimulgus",
        "Erebus crepuscularis", "Erebus ephesperis", "Ommatophora luminosa", "Cruriopsis funebris", "Checupa stegeri",
        "Ischyja ferrifracta", "Narangodes confluens", "Adris okurai", "Sarcopteron punctimargo", "Catocala fraxini", "Thyas honesta",
        "Eudocima salaminia", "", "Eudocima phalonia", "Yepcalphis dilectissima", "Arcte coerula", "", "Spodoptera frugiperda",
        "Xylostola indistincta", "Achaea janata", "Ischyja manlia", "Catocala electa", "Heliophobus dissectus", "Baorisa hieroglyphica",
        "Scrobigera", "Sinna extrema", "Sinna floralis", "Apsarasa radians", "Thysanoplusia daubei", "Tiracola aureata",
        "Anacronicta nitida", "Anacronicta horishana", "Edessena hamada", "Serrodes campana", "Gabala argentata", "Othreis homaena", "",
        "Asota plana", "Asota plana", "Daseochaeta pulchra", "Diphtherocome", "Hypena", "Hypena trigonalis", "Hypena vestita",
        "Hypena lignealis", "Hypena amica", "Hypena indicatalis", "Hypena albopunctalis", "Hypena strigatus", "Hypena perspicua",
        "Hypena obesalis", "Hypena lividalis", "Hypena laceratalis", "Sympis rufibasis", "Saturniidae", "Attacus atlas",
        "Graellsia isabellae", "Antheraea yamamai", "Actias sinensis", "Caligula simla", "Antheraea polyphemus", "Actias maenas",
        "Cricula andrei", "", "Argema mittrei", "Actias luna", "Antheraea pernyi", "Samia", "", "Automeris io", "", "", "Saturnia thibeta",
        "Loepa", "Loepa oberthuri", "Loepa megacore", "Antheraea assamensis", "Dictyoploca japonica(Caligula japonica)", "", "Sphingidae",
        "Marumba saishiuana", "Marumba sperchius", "Marumba dyras", "Marumba cristata", "Meganoton analis", "Hayesiana triopus",
        "Eupanacra mydon", "Theretra oldenlandiae", "", "Theretra alecto subsp. cretica", "Theretra latreillei", "Theretra silhetensis", "",
        "Theretra tibetiana", "Theretra pallicosta", "Theretra japonica", "Theretra nessus", "Hippotion rafflesii", "Hippotion rosetta",
        "Hippotion celerio", "Pergesa acteus", "", "Dolbina inexacta", "Dolbina tancrei", "Sphecodina caudata", "Parum colligata", "",
        "Cypoides", "Callambulyx tatarinovii", "Agrius convolvuli", "", "Rhagastis", "Daphnis nerii", "", "Daphnis hypothous",
        "Smerinthus caecus", "Smerinthus planus", "Phyllosphingia", "Deilephila elpenor", "Angonyx testacea", "Acosmeryx formosana",
        "Acosmeryx castanea", "Acosmeryx naga", "Acosmeryx miskini", "Cechenena minor", "Cechenena lineosa", "Cechenena subangustata",
        "Amplypterus panopus", "Ampelophaga rubiginosa", "Clanis", "Cephonodes hylas", "Nephele hespera", "Langia zenzeroides",
        "Macroglossum", "Macroglossum fritzei", "Macroglossum stellatarum", "Macroglossum passalus", "", "Macroglossum bombylans",
        "Macroglossum pyrrhosticta", "", "Psilogramma increta", "Psilogramma menephron", "Acherontia styx", "Acherontia atropos", "",
        "Acherontia lachesis", "", "Ambulyx", "Haemorrhagiae", "Ethmia lineatonotella", "Labdia semicoccinea", "Geometridae",
        "Mixochlora vittata", "Sarcinodes aequilinearia", "Abraxas suspecta", "Xanthabraxas hemionata", "Plutodes", "Plutodes flavescens",
        "Plutodes exquisita", "Plutodes costatus", "Gandaritis fixseni", "Semiothisa emersaria", "Paramaxates", "Biston comitata",
        "Megaspilates mundataria", "Neohipparchus vallata", "Cleora cinctaria", "Chlorodontopera discospilata", "Semiothisa intermediaria",
        "Dalima patularia", "Terpna subtrita", "Ectropis excellens", "Percnia cordiforma", "Naxa seriaria", "Herochroma cristata",
        "Herochroma supraviridaria", "Psyra conferta", "Jankowskia fuscaria", "Idaea muricata", "Hypomecis punctinalis",
        "Ourapteryx sambucaria", "Ourapteryx nigrociliaris", "Ourapteryx clara", "Ourapteryx nivea", "Scopula yamanei", "Dindica taiwana",
        "Dindica polyphaenaria", "Ophthalmitis cordularia", "Agnibesa pictaria", "Eucyclodes semialba",
        "Eucyclodes gavissima(Chloromachia gavissima)", "Antipercnia albinigrata", "Plagodis dolabraria", "Telenomeuta punctimarginaria",
        "Hemithea tritonaria", "Oxymacaria temeraria", "Dooabia lunifera", "Biston panterinaria", "Deileptenia ribeata",
        "Percnia giraffata", "", "Erebomorpha fulguraria", "Ophthalmitis albosignaria", "Chiasmia hebesata", "Phthonandria atrilineata",
        "Apochima excavata", "", "Abraxas sylvata", "Thalassodes antiquadraria", "Inurois membranaria", "Chiasmia defixaria",
        "Catoria olivescens", "Myrteta angelica", "Hydrelia bicauliata", "Hydrelia bicolorata", "Hydrelia ulula", "Hydrelia enisaria",
        "Hydrelia flammeolaria", "Evecliptopera decurrens", "Biston suppressaria", "Biston marginata", "Uliocnemis castalaria",
        "Nycterosea obstipata", "Ninodes splendens", "Tyloptera bella", "Chartographa", "Ectropis bhurmitra", "Biston perclara",
        "Myrteta tinagmaria", "Thalassodes immissaria", "Percnia suffusa", "Bizia aexaria", "Electrophaes zaphenges",
        "Electrophaes corylata", "Xandrames latiferaria", "Xandrames dholaria", "Cyclothea disjuncta", "Stegania cararia",
        "Lophomachia lalashana", "Abraxaphantes perampla", "Operophtera relegata", "Krananda latimarginaria", "Krananda semihyalina",
        "Krananda lucidaria", "Colotois pennaria", "Amblychia angeronaria", "Dischidesia cinerea", "Problepsis", "Problepsis vulgaris",
        "Problepsis superans", "Problepsis albidior", "Ennomos autumnaria", "Corymica", "Pingasa ruginaria", "Pingasa alba", "Idaea impexa",
        "Fascellina chromataria", "", "Palpoctenidia phoenicosoma", "Berta rugosivalva", "Timandra dichela", "Timandra stueningi",
        "Timandra convectaria", "Timandra synthaca", "Timandra comptaria", "Timandra recompta", "Comibaena", "Comibaena pictipennis",
        "Comostola subtiliaria", "Comibaena nigromacularia", "Comibaena procumbaria", "Hemistola monotona", "Fascellina plagiata",
        "Tanaoctenia haliaria", "Episothalma robustaria", "Aporandria specularia", "Hypochrosis hyadaria", "Capasa festivaria",
        "Gnamptoloma aventiaria", "", "Timandromorpha discolor", "Laciniodes plurilinearia", "Ascotis selenaria", "Xenoplia trivialis",
        "Agathia", "Agathia lycaenaria", "Agathia hilarata", "Agathia arcuata", "Agathia laetata", "Agathia diversiformis",
        "Agathia carissima", "Milionia basalis", "Cystidia", "Pseudomiza aurata", "Chorodna creataria", "Hydatocapnia gemina",
        "Tephrina inchoata", "Metallolophia arenaria", "Dysphania militaris", "Obeidia tigrata", "Obeidia gigantearia", "Obeidia lucifera",
        "Odontopera insulata", "Odontopera bilinearia", "Culpinia diffusa", "Iotaphora", "Spilopera divaricata", "Plesiomorpha flaviceps",
        "", "Acolutha pulchella subsp. semifulva", "Hyposidra aquilaria", "Heterolocha aristonaria", "Ophthalmitis herbidaria",
        "Auaxa cesadaria", "Tanaorhinus viridiluteata", "Tanaorhinus kina", "Tanaorhinus rafflesii", "Tanaorhinus reciprocata",
        "Sibatania arizana", "Eumelea ludovicata", "Alcis angulifera", "Alcis repandata", "Heterolocha coccinea",
        "Trichopteryx polycommata", "Opisthograptis moelleri", "Garaeus specularis", "Zanclopera falcata", "Arichanna melanaria",
        "Nothomiza flavicosta", "", "Thinopteryx crocoptera", "Eilicrinia flava", "Borbacha pardaria", "Hyposidra infixaria",
        "Cleora fraterna", "Medasina corticaria", "Yponomeutidae", "Yponomeuta evonymella", "Yponomeuta padella", "Hesperiidae",
        "Burara gomata", "Baoris farri", "Udaspes folus", "Polytremis lubricans", "Badamia exclamationis", "Isoteinon lamprospilus",
        "Celaenorrhinus maculosus", "Mooreana trichoneura", "Matapa aria", "Erynnis montanus", "Erynnis tages", "Seseria dohertyi",
        "Abraximorpha davidii", "Parnara naso", "Parnara ganga", "Parnara guttata", "Borbo cinnara", "Suastus gremius", "",
        "Astictopterus jama", "Erionota torus", "Notocrypta curvifascia", "Tagiades litigiosa", "Tagiades menaka", "Pseudocoladenia dan",
        "Odontoptilum angulatum", "Pelopidas", "Pelopidas agna", "Pelopidas conjuncta", "Pelopidas mathias", "Hasora badra",
        "Hasora chromus", "Hasora anura", "Hasora vitta", "Halpe porus", "Ancistroides nigrita", "Telicota besta", "Telicota colon",
        "Telicota ohara", "Iambrix salsala", "Potanthus confucius", "Potanthus trachala", "Ampittia virgata", "Daimio tethys", "Zygaenidae",
        "", "Erasmia pulchella", "", "Pryeria sinica", "Pidorus", "Campylotes", "Phauda flammans", "", "Elcysma westwoodi",
        "Thyrassia penangae", "", "Artona hainana", "Trypanophora semihyalina", "", "Eterusia aedea", "", "Clelea sapphirina",
        "Cyclosia midama", "Cyclosia papilionaris", "Cyclosia papilionaris", "Cyclosia panthona", "Amesia sanguiflua", "Histia rhodope",
        "Gynautocera papilionaria", "Soritia strandi", "Soritia strandi", "Rhodopsona rubiginosa", "Idea leuconoe", "Danaus genutia",
        "Danaus chrysippus", "", "Danaus plexippus", "Ideopsis similis", "Ideopsis vulgaris", "Euploea", "Euploea sylvester",
        "Euploea tulliolus", "Euploea core", "Euploea mulciber", "Euploea midamus", "Parantica", "Parantica sita", "Parantica swinhoei",
        "Parantica aglea", "Parantica melaneus", "Tirumala septentrionis", "Tirumala limniace", "Cossidae", "Zeuzera coffeae",
        "Zeuzera multistrigata", "Zeuzera pyrina", "Lasiocampidae", "Gastropacha quercifolia", "Gastropacha populifolia", "Trabala vishnou",
        "", "Gastropacha pardale", "Lebeda nobilis", "", "Euthrix laeta", "Metanastria gemella", "", "Odonestis pruni", "Euthrix isocyma",
        "Cosmotriche discitincta", "Lymantriidae", "Calliteara pudibunda", "Calliteara horsfieldii", "Calliteara horsfieldii",
        "Calliteara grotei", "Calliteara grotei", "Arna bipunctapex", "Orgyia antiqua", "Orgyia antiqua", "Orgyia postica",
        "Orgyia postica", "Olene mendosa", "Olene mendosa", "Leucoma salicis", "Lymantria mathura", "Lymantria mathura#幼虫",
        "Lymantria concolor", "Lymantria dispar", "Lymantria dispar", "Lymantria marginata", "Dasychira suisharyonis",
        "Dasychira suisharyonis", "Arctornis l-nigrum", "Laelia coenosa", "Olene dudgeoni", "Olene dudgeoni", "Cifuna locuples",
        "Euproctis similis", "Euproctis similis", "Habrosyne pyritoides", "Parapsestis tomponis", "Thyatira batis", "Tethea consimilis",
        "Arctiidae", "Phragmatobia luctifera", "Areas galactina", "Peridrome subfascia", "Phragmatobia fuliginosa",
        "Phragmatobia fuliginosa", "Ammatho tairadiata", "Peridrome orbicularis", "Eilema costipuncta", "Nudaria ranruna",
        "Aglaomorpha histrio", "Utetheisa lotrix", "Pericallia matronula", "Asota plaginota", "Spilosoma lubricipeda", "Asota ficus",
        "Asota egens", "Pelosia muscerda", "Arctia flavia", "Arctia caja", "Eilema griseola", "Creatonotus transiens", "Creatonotos gangis",
        "Stictane rectilinea", "Rhyparioides metelkana", "Agrisius fuliginosus", "Stigmatophora palmata", "Stigmatophora flava",
        "Vamuna remelana", "Aloa lactinea", "Spilosoma subcarnea", "", "Tyria jacobaeae", "", "Macrobrochis gigas", "", "Hyphantria cunea",
        "Hyphantria cunea", "Miltochrista", "Miltochrista sauteri(Barsine sauteri)", "Miltochrista ziczac", "Miltochrista convexa",
        "Miltochrista fuscozonata", "Miltochrista miniata", "Mangina argus", "Teulisna tumida", "Eugoa grisea", "", "Nyctemera lacticinia",
        "Nyctemera lacticinia", "Nyctemera baulus", "Nyctemera tripunctaria", "Nyctemera adversata", "Euplocia membliaria",
        "Amerila astreus", "Chrysaeglia magnifica", "Neochera dominia", "Paraona staudingeri", "Cyana", "Cyana hamata", "Cyana propinqua",
        "Spilosoma taiwanensis", "Lycaenidae", "Ticherra acte", "Amblopala_avidiena", "Miletus_chinensis", "Lampides boeticus",
        "Creon cleobis", "Tajuria cippus", "Zizeeria karsandra", "Catochrysops strabo", "Catochrysops panormus", "Poritia erycinoides",
        "Udara dilectus", "Udara albocaerulea", "Arhopala paramuta", "Arhopala bazala", "Arhopala rama", "Nacaduba kurava",
        "Nacaduba berenice", "Plebejus orbitulus", "Ancema blanka", "Iraota timoleon", "Heliophorus", "Heliophorus brahma",
        "Heliophorus epicles", "Heliophorus ila", "heliophorus saphir", "Caleta roxus", "Horaga onyx", "Horaga albimacula",
        "Yasoda tripunctata", "Zizeeria otis", "Prosotas nora", "Lycaena dispar", "Lycaena phlaeas", "Neopithecops zalmora", "Rapala",
        "Rapala suffusa", "Rapala nissa", "Tongeia potanini", "Tongeia filicaudis", "Tongeia fischeri", "Mahathala ameria",
        "Deudorix epijarbas", "Pratapa deva", "Zeltus amasa", "Scolitantides orion", "Celastrina argiolus", "Sinthusa chandrana",
        "Chilades pandava", "Tarucus plinius", "Artipe eryx", "Megisba malaya", "Remelana jangala", "Everes argiades", "Taraka hamada",
        "Plebejus argyrognomon", "Ussuriana michaelis", "Pseudozizeeria maha", "Acytolepis puspa", "Teratozephyrus arisanus",
        "Curetis acuta", "Spindasis", "Spindasis syama", "Allotinus_drumila", "Aeromachus pygmaeus", "Aeromachus inachus", "Zizula hylax",
        "Jamides alecto", "Jamides celeno", "Jamides bochus", "Spialia galba", "Loxura atymnus", "Niphanda fusca", "Dysaethria erasaria",
        "Urapteroides astheniata", "Orudiza protheclaria", "Lyssa zampa", "Acropteris leptaliata", "Acropteris iphiata",
        "Warreniplema fumicosta", "Urania leilus", "Chrysiridia rhipheus", "Amathusiidae", "Faunis eumeus", "Faunis aerope",
        "Faunis canens", "Thauria lathyi", "Thaumantis diores", "Discophora sondaica", "Stichophthalma howqua", "Aemona amathusia",
        "Acraea violae", "Acraea terpsicore", "Acraea issoria", "", "Siglophora sanguinolenta", "Westermannia elliptica",
        "Risoba prominens", "Blenina quinaria", "Blenina senex", "Iragaodes nobilis", "Carea varipes", "Satyridae", "Neorina patria",
        "Mandarinia regalis", "Penthema formosanum", "Penthema darlisa", "Penthema adelma", "Melanitis leda", "Melanitis phedima",
        "Coenonympha amaryllis", "Melanargia", "Melanargia galathea", "Mycalesis intermedia", "Mycalesis sangaica", "Mycalesis anaxias",
        "Mycalesis mineus", "Mycalesis zonata", "Mycalesis francisca", "Mycalesis gotama", "Mycalesis perseus", "Ypthima",
        "Ypthima motschulskyi", "Ypthima praenubila", "Ypthima baldus", "Callerebia", "Neope", "Neope bremeri", "Neope muirheadii",
        "Neope pulaha", "Elymnias hypermnestra", "Aphantopus hyperantus", "Lethe", "Lethe mekara", "Lethe butleri", "Lethe gemina",
        "Lethe sinorix", "Lethe vindhya", "Lethe chandica", "Lethe christophi", "Lethe rohria", "Lethe insana", "Lethe verma",
        "Lethe confusa", "Lethe lanaris", "Lethe syrcis", "Lethe europa", "Lethe dura", "Brahmaeidae", "Brahmaea wallichii",
        "Brahmaea porphyrio", "Brahmaea hearseyi", "Brahmaea certhia", "Pieridae", "Pontia daplidice", "Pontia chloridice",
        "Leptidea sinapis", "Leptidea amurensis", "Leptidea morsei", "Appias libythea", "Appias lyncida", "Appias albina", "Appias nero",
        "Delias hyparete", "Delias pasithoe", "Delias descombesi", "Delias acalis", "Delias belladonna", "Dercas verhuelli", "Ixias pyrene",
        "Gandaca harina", "Pieris canidia", "Pieris napi", "Pieris rapae", "Pieris melete", "Leptosia nina", "Aporia", "Aporia agathon",
        "Aporia crataegi", "Anthocharis bambusarum", "Anthocharis scolymus", "Colias erate", "Colias fieldii", "Colias hyale",
        "Colias palaeno", "Catopsilia pyranthe", "Catopsilia pomona", "Catopsilia scylla", "Gonepteryx amintha", "Gonepteryx rhamni",
        "Prioneris thestylis", "Pareronia valeria", "Hebomoia glaucippe", "Eurema mandarina", "Eurema andersoni", "Eurema hecabe",
        "Eurema laeta", "Eurema brigitta", "Eurema blanda", "Cepora nerissa", "Promalactis suzukiella", "Scythris sinensis",
        "Eretmocera impactella", "Parnassius", "Parnassius citrinarius", "Parnassius nomion", "Parnassius phoebus", "Parnassius bremeri",
        "Parnassius apollonius", "Parnassius apollo", "Thyrididae", "Striglina scitaria", "Thyris fenestrella", "Pyrinioides sinuosa",
        "Pterophoridae", "Saptha divitiosa", "Notodontidae", "Gazalina chrysolopha", "Cerura menciana", "Cerura vinula", "",
        "Syntypistis subgeneris", "Shachihoka formosana", "Clostera anastomosis", "Formofentonia orbifer", "Quadricalcarifera viridipicta",
        "Mimopydna", "Phalera", "Phalera grotei", "Phalera bucephala", "Phalera assimilis", "Phalera flavescens", "Pheosia rimosa",
        "Clostera anachoreta", "Fentonia ocypete", "Netria viridescens", "Syntypistis comatus", "Clostera albosigma", "Rachia striata",
        "Ptilodon saturata", "Uropyia meticulodina", "Spatalia doerriesi", "Stauropus fagi", "Syntypistis pallidifascia",
        "Gonoclostera timoniorum", "Gangarides", "Euhampsonia splendida", "Ginshachia elongata", "Euhampsonia cristata",
        "Dudusa sphingiformis", "Patania chlorophanta", "Paracymoriza cataclystalis", "Pycnarmon lactiferalis", "Heterocnephes lymphatalis",
        "Pagyda quinquelineata", "Cotachena histricalis", "Anania funebris", "Talanga sexpunctalis", "Agathodes ostentalis",
        "Syllepte taiwanalis", "Nagiella quadrimaculalis", "Glyphodes quadrimaculalis", "Cirrhochrista brizoalis", "Polythlipta liquidalis",
        "Botyodes principalis", "Eoophyla gibbosalis", "Eoophyla conjunctalis", "Parapediasia teterrellus", "Syllepte iophanes",
        "Glyphodes duplicalis", "Pleuroptya balteata", "Glyphodes pyloalis", "Syllepte derogata", "Ramila acciusalis", "Tyspanodes striata",
        "Cotachena pubescens", "Herpetogramma licarsisalis", "Pachynoa sabelialis", "Pycnarmon cribrata", "Paracymoriza prodigalis",
        "Diaphania indica", "Omphisa anastomosalis", "Botyodes asialis", "Cangetta rectilinea", "Agrioglypta itysalis",
        "Cnaphalocrocis medinalis", "Crypsiptya coclesalis", "Parapoynx stagnalis", "Parapoynx fluctuosalis", "Parapoynx vittalis",
        "Parapoynx crisonalis", "Parapoynx villidalis", "Parapoynx diminutalis", "Pleuroptya iopasalis", "Palpita",
        "Palpita nigropunctalis", "Nevrina procopia", "Nosophora semitritalis", "Loxostege sticticalis", "Poliobotys ablactalis",
        "Diplopseustis perieresalis", "Pagyda nebulosa", "Cyrtogramme turbata", "Agrotera scissalis", "Pleuroptya ruralis",
        "Maruca vitrata", "Pycnarmon pantherata", "Pseudargyria interruptella", "Eumorphobotys eumorphalis", "Botyodes diniasalis",
        "Goniorhynchus butyrosa", "Triuncina brunnea", "Bombyx mandarina", "Bombyx mandarina", "Rondotia menciana", "", "Riodinidae",
        "Dodona", "Dodona egeon", "Dodona maculosa", "Dodona durga", "Dodona eugenes", "Zemeros flegyas", "Stiboges nymphidia",
        "Abisara saturata", "Abisara fylloides", "Abisara burnii", "Abisara echerius", "Abisara bifasciata", "Abisara neophron",
        "Abisara fylla", "Nymphalidae", "银纹红袖蝶 Agraulis vanillae", "Cyrestis cocles", "Cyrestis thyodamas", "Cyrestis nivea",
        "Parthenos syvia", "Parasarpa dudu", "Chersonesia risa", "Chalinga", "Abrota ganga", "Siproeta stelenes", "Boloria titania",
        "Brenthis daphne", "Polyura narcaea", "Polyura eudamippus", "Polyura nepenthes", "Polyura athamas", "Sephisa chandra",
        "Sephisa princeps", "Pararge aegeria", "Terinos atlita", "Athyma", "Athyma cama", "Athyma zeroca", "Athyma selenophora",
        "Athyma perius", "Athyma asura", "Athyma nefte", "Athyma ranga", "Athyma opalina", "Vagrans egista", "Lexias pardalis",
        "Vindula erota", "Argyreus hyperbius", "Asterocampa celtis", "Hypolimnas bolina", "Hypolimnas missipus", "Kallima inachus",
        "Euphaedra themis", "Ariadne ariadne", "Ariadne merione", "Diaethria", "Herona marathus", "Timelaea", "Timelaea albescens",
        "Neptis", "Neptis hylas", "Neptis soma", "Neptis namba", "Neptis nata", "Neptis sappho", "Neptis miah", "Neptis sankara",
        "Neptis clinia", "Neptis pryeri", "Tanaecia julii", "Tanaecia jahnu", "Clossiana freija", "Clossiana euphrosyne", "Clossiana dia",
        "Phalanta phalantha", "Issoria eugenia", "Issoria lathonia", "Kaniska canace", "Prothoe franck", "Dichorragia nesimachus",
        "Helcyra subalba", "Symbrenthia lilaea", "Symbrenthia brabira", "Junonia atlites", "Junonia almana", "Junonia orithya",
        "Junonia lemonias", "Junonia iphita", "Junonia coenia", "Junonia coenia", "Junonia hierta", "Fabriciana adippe",
        "Pseudergolis wedah", "Moduza procris", "Dilipa fenestra", "Sasakia charonda", "Sasakia funebris", "Vanessa atalanta",
        "Vanessa indica", "Vanessa cardui", "Vanessa virginiensis", "Limenitis", "Limenitis doerriesi", "Limenitis sulpitia",
        "Limenitis populi", "Calinaga buddha", "Dophla evelina", "Melitaea", "Rohana parisatis", "Euthalia", "Euthalia", "Euthalia phemius",
        "Euthalia pratti", "Euthalia aconthea", "Euthalia lubentina", "Euthalia niepelti", "Argyronome laodice", "Bhagadatta austenia",
        "Hestina persimilis", "Hestina nama", "Hestina assimilis", "Phaedyma columella", "Hamadryas", "Nymphalis xanthomelas",
        "Nymphalis vau-album", "Nymphalis antiopa", "", "Araschnia doris", "Araschnia prorsoides", "Araschnia levana", "Charaxes bernardus",
        "Charaxes bernardus", "Pantoporia hordonia", "Doleschallia bisaltide", "Heliconius erato", "Heliconius charithonia",
        "Cupha erymanthis", "Cupha erymanthis", "Argynnis paphia", "Argynnis aglaja", "Mimathyma schrenckii", "Polygonia c-album",
        "Polygonia c-aureum", "Proclossiana eunomia", "Chitoria ulupi", "Cethosia cyane", "Cethosia biblis", "Apatura ilia", "Apatura iris",
        "Damora sagana", "Stibochiona nicea", "Aglais io", "Aglais urticae", "Lebadea martha", "Pyralidae", "Mabra charonialis",
        "Plodia interpunctella", "Eurrhyparodes bracteolalis", "Aethaloessa calidalis", "Endotricha olivacealis", "Ostrinia palustralis",
        "Spoladea recurvalis", "Bocchoris inspersalis", "Arippara indicator", "Ancylolomia japonica", "Circobotys aurealis",
        "Oncocera semirubella", "Heortia vitessoides", "Locastra muscosalis", "Nosophora insignis", "Orybina regalis",
        "Rhectothyris gratiosalis", "Leucinodes orbonalis", "Herpetogramma luctuosalis", "Conogethes punctiferalis", "Pyralis pictalis",
        "Pyralis farinalis", "Pyralis regalis", "Diasemia accalis", "Apomyelois ceratoniae", "Omiodes indicata", "Orybina flaviplaga",
        "Lista haraldusalis", "Eurrhyparodes tricoloralis", "Rehimena phrynealis", "Cydalima perspectalis", "", "Tyspanodes hypsalis",
        "Lamprosema commixta", "Bocchoris onychinalis", "Ericeia inangulata", "Gesonia obeditalis", "Eublemma anachoresis",
        "Nagadeba indecoralis", "Lagoptera juno", "Artena dotata", "Scoliopteryx libatrix", "Eublemma cochylioides", "Oruza glaucotorna",
        "Autoba tristalis", "Paracolax pryeri", "Ercheia umbrosa", "Cruxoruza decorata", "Opogona nipponica", "Sesiidae",
        "Paranthrene tabaniformis", "Drepanidae", "Drepana pallida", "Pseudalbara parvula", "Canucha miranda", "Callidrepana patrana",
        "Oreta insignis", "Cyclidia substigmaria", "Cyclidia orciferaria", "Macrauzata maxima", "Oreta loochooana", "Nordstromia japonica",
        "Ditrigona triangularia", "Macrocilix mysticata", "Deroca hidda", "Drepana curvatula", "Agnidra scabiosa", "Macrocilix maia",
        "Drapetodes mitaria", "", "Petavia attenuata", "Tetragonus catamitus", "Adelidae", "Lepidotarphius perornatellus", "Ctenuchidae",
        "Syntomoides imaon", "Amata sperbius", "Amata germana", "Amata fortunei", "Amata grotei", "Anacampsis populella",
        "Dichomeris sandycitis"
    };
  };
}


#endif //LITE_AI_TOOLKIT_MNN_CV_MNN_INSECTID_H
