//
// Created by DefTruth on 2021/11/21.
//

#ifndef LITE_AI_TOOLKIT_MNN_CV_MNN_FACE_LANDMARKS_1000_H
#define LITE_AI_TOOLKIT_MNN_CV_MNN_FACE_LANDMARKS_1000_H

#endif //LITE_AI_TOOLKIT_MNN_CV_MNN_FACE_LANDMARKS_1000_H
