//
// Created by DefTruth on 2021/11/13.
//

#ifndef LITE_AI_TOOLKIT_MNN_CV_MNN_GLINT_ARCFACE_H
#define LITE_AI_TOOLKIT_MNN_CV_MNN_GLINT_ARCFACE_H

#endif //LITE_AI_TOOLKIT_MNN_CV_MNN_GLINT_ARCFACE_H
