//
// Created by DefTruth on 2021/11/14.
//

#ifndef LITE_AI_TOOLKIT_MNN_CV_MNN_CAVA_GHOST_ARCFACE_H
#define LITE_AI_TOOLKIT_MNN_CV_MNN_CAVA_GHOST_ARCFACE_H

#endif //LITE_AI_TOOLKIT_MNN_CV_MNN_CAVA_GHOST_ARCFACE_H
